language: python
os:
- linux
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install flake8
install:
- pip install .
stages:
- lint
jobs:
  include:
  - stage: lint
    script: flake8 --max-line-length 120
script: echo "Success!"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: cAdXcV3qAznVzaqKAFLumyeFZ8mBvgUtKqBlMmeUJdkfnHdISabeVGOKskvbE3yIs2IyMIPzZbqwGSAQ3R28pxbP4vn4EgMQJDmKE4Zqce93hMSChFWRZu8lC333DLMJoIfGezrrTcbs3hnz2r8KEjOy7SNtRcMdjvwC/HuvKDhczPpNWj4XxvjsBhfLcXk4ZLBFE2oxKEHlRJj6Xo70S6w4zOvNt6XNm6CwLB4aPnXO4T5uZt8aczheqtPwmFoeSguC95hTkjKxS+HK9ga+uHG1Gjcr6cV2BsHWLqFYCyIGZNDrmA8Ggp/lIKU+NHGjQlrF1sXe/p65DKa25cwFZcCwdwjat63ImKl4DhIn8CNY876kAZyKa2cwIqNKSfosSs/Ln4uTkQjpz217qy816gIuXZJDH11w5MbbA1xYT6xLhIkkfMxTsnnvA9wlKIfG4cf3t5QUWDHTHtaFf9TjEV7Ngt7mE6gtW2zmL8w8dVwaBoKrUtIuAZ7rFvoFgmQDJiXjnxoASJfBsEIb55USTQXZf1neW1TOO8eDDClQP4SJX5nqi6RrvsW1kCU2prNktjLGd5Wp5rpwHE/LnijSL4Ossqpw9FluZx86T77Kpz2sNkqGNu1sH/+F+deACpA+OtUk1Uv2M9pURRhjOJDQ+yHTCjFYIdKvCVDoNHfFnNs=
  on:
    tags: true
  skip_existing: true
